name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter build apk --debug
    - uses: actions/upload-artifact@v1
      with:
        name: apk
        path: build/app/outputs/apk

    - name: Push app to appetize
       id: upload
       uses: JantHsueh/upload-file-action@master
       with:
         url: ${{ format('https://{0}@api.appetize.io/v1/apps/nye19v8gw59wkabxjzmk9pdrp0', secrets.APPETIZE_TOKEN) }}
         forms: '{"platform":"android"}'
         fileForms: '{"file":"build/app/outputs/apk/debug/app-debug.apk"}'
